basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a simple football league simulation API.
  title: Insider API
  version: "1.0"
paths:
  /predict-champion-before-last-week:
    get:
      description: Predicts the champion before the last week
      responses: {}
      summary: Predicts the champion before the last week
      tags:
      - routes
  /simulate:
    get:
      description: Simulates the matches between the teams
      responses: {}
      summary: Simulates the matches between the teams
      tags:
      - routes
swagger: "2.0"
